### ISSUE TITLE
Unable to get this working

### ISSUE THREAD

**Issue by john-doherty** [jshor/symbology#9]
Hi Josh, I love the idea of this module but I can't get it working using the following:

```js
// create temp file
var tmpFile = path.resolve(path.join(tmpFolder, (new Date().getTime()) + '.png'));

// setup options
var opts = {
    symbology: symbology.Barcode.CODE128,
    foregroundColor: 'fff000',
    backgroundColor: '000000',
    fileName: tmpFile
};

// create file
symbology.createFile(opts, data, 'png').then(function(result) {
    console.log(result);
})
.catch(function(err) {
    console.log(err);
});
```

Output:

```js
{
    code:2,
    fileName:"/var/folders/2p/b__k79vs73j04x7lx_zjwnlm0000gn/T/1537561690583.png",
    inputData:"11110010010",
    message:""
}
```

Any ideas?

**Comment by john-doherty** [comment]
The above code writes the following to the `.png` file

```bash
%!PS-Adobe-3.0 EPSF-3.0
%%Creator: Symbology.js%%Title: 12345
%%Pages: 0
%%BoundingBox: 0 0 79 59
%%EndComments
/TL { setlinewidth moveto lineto stroke } bind def
/TC { moveto 0 360 arc 360 0 arcn fill } bind def
/TH { 0 setlinewidth moveto lineto lineto lineto lineto lineto closepath fill } bind def
/TB { 2 copy } bind def
/TR { newpath 4 1 roll exch moveto 1 index 0 rlineto 0 exch rlineto neg 0 rlineto closepath fill } bind def
/TE { pop pop } bind def
newpath
0.00 0.00 0.00 setrgbcolor
1.00 0.94 0.00 setrgbcolor
59.00 0.00 TB 0.00 79.00 TR
TE
0.00 0.00 0.00 setrgbcolor
50.00 9.00 TB 0.00 2.00 TR
TB 3.00 1.00 TR
TB 6.00 3.00 TR
TB 11.00 1.00 TR
TB 13.00 2.00 TR
TB 17.00 3.00 TR
TB 22.00 1.00 TR
TB 26.00 1.00 TR
TB 28.00 2.00 TR
TB 33.00 1.00 TR
TB 35.00 4.00 TR
TB 40.00 3.00 TR
TB 44.00 2.00 TR
TB 47.00 3.00 TR
TB 52.00 1.00 TR
TB 55.00 3.00 TR
TB 59.00 1.00 TR
TB 61.00 2.00 TR
TB 66.00 2.00 TR
TB 71.00 3.00 TR
TB 75.00 1.00 TR
TB 77.00 2.00 TR
TE
0.00 0.00 0.00 setrgbcolor
matrix currentmatrix
/Helvetica findfont
8.00 scalefont setfont
 0 0 moveto 39.50 0.50 translate 0.00 rotate 0 0 moveto
 (12345) stringwidth
pop
-2 div 0 rmoveto
 (12345) show
setmatrix

showpage

```

**Comment by john-doherty** [comment]
@jshor thanks for the update and sorry to be a pain, but I just tried to install the latest from via npm using **npm install symbology --save** but now get the following:

```
make: *** No rule to make target `Release/obj.target/symbology/src/lib/zint/2of5.o', needed by `Release/symbology.node'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/JD/Projects/test-project/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/JD/.nvm/versions/node/v9.1.0/lib/node_modules/node/lib/node_modules/node/lib/node_modules/node/bin/node" "/Users/JD/Projects/test-project/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/JD/Projects/test-project/node_modules/symbology/lib/binding/Release/symbology.node" "--module_name=symbology" "--module_path=/Users/JD/Projects/test-project/node_modules/symbology/lib/binding/Release" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v59"
gyp ERR! cwd /Users/JD/Projects/test-project/node_modules/symbology
gyp ERR! node -v v9.11.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/JD/.nvm/versions/node/v9.1.0/lib/node_modules/node/lib/node_modules/node/lib/node_modules/node/bin/node /Users/JD/Projects/test-project/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/JD/Projects/test-project/node_modules/symbology/lib/binding/Release/symbology.node --module_name=symbology --module_path=/Users/JD/Projects/test-project/node_modules/symbology/lib/binding/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v59' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/JD/Projects/test-project/node_modules/symbology/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:936:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/Users/JD/.nvm/versions/node/v9.1.0/lib/node_modules/node/lib/node_modules/node/lib/node_modules/node/bin/node" "/Users/JD/Projects/test-project/node_modules/symbology/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/JD/Projects/test-project/node_modules/symbology
node-pre-gyp ERR! node -v v9.11.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/Users/JD/.nvm/versions/node/v9.1.0/lib/node_modules/node/lib/node_modules/node/lib/node_modules/node/bin/node /Users/JD/Projects/test-project/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/JD/Projects/test-project/node_modules/symbology/lib/binding/Release/symbology.node --module_name=symbology --module_path=/Users/JD/Projects/test-project/node_modules/symbology/lib/binding/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v59' (1)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! symbology@1.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the symbology@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

I'm using a mac with High Sierra 10.

**Comment by jshor** [comment]
@john-doherty it looks like the Travis setup is configured incorrectly and didn't push the release to S3; still working through it, thanks for being patient :)

**Comment by john-doherty** [comment]
No worries @jshor, appreciate you taking the time to resolve this!

**Comment by jshor** [comment]
@john-doherty can't test the binary right now because of a firewall, but v1.2.2 is released and should be functional

**Comment by jshor** [comment]
@john-doherty closing this issue as installation/running appears to work properly. I've eliminated the libpng dependency so as long as `gcc` is available this node module should compile properly. Feel free to re-open this issue if install/running still fails for you however

**Comment by john-doherty** [comment]
Hi Josh, finally got some time to look at this again.

I'm still having an issue trying to install via npm, I now get:

```bash
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://symbologyjs.s3-us-west-2.amazonaws.com/symbology/v1.2.3/Release/symbology-v1.2.3-node-v59-darwin
-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for symbology@1.2.3 and node@9.11.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp)
gyp info it worked if it ends with ok
```
